### ISSUE TITLE
[Bug]: default_bus: setono_sylius_pickup_point.command_bus

### ISSUE THREAD

**Issue by Geolim4** [Setono/SyliusPickupPointPlugin#107]
### Plugin version

latest

### Sylius version

1.13.7

### What happened?

Hello,

In API platform context I got this error caused by the SyliusPickupPointPlugin:
```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Messenger\Exception\NoHandlerForMessageException: "No handler for message "Sylius\Bundle\ApiBundle\Command\Account\RegisterShopUser"." at HandleMessageMiddleware.php line 117 {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\NoHandlerForMessageException(code: 0): No handler for message \"Sylius\\Bundle\\ApiBundle\\Command\\Account\\RegisterShopUser\". at /data/www/root/xxxxx.xxxxxxxxxxxxxxxx/releases/282/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:117)"} []
```

This is typically caused by your config.yml overriding the Sylius default's config:
```
framework:
    messenger:
        default_bus: setono_sylius_pickup_point.command_bus
```

Is there a specific reason for that ?

Cheers,
Georges

**Comment by loevgaard** [comment]
Yes, that shouldn't be your default bus :)

**Comment by loevgaard** [comment]
Where do we set the default bus in this plugin? Can't find it right now.

**Comment by Geolim4** [comment]
Ahhh my bad, one of our developers forked it to an internal vcs...
I'm gonna slap its head the whole journey.

My apologizes !
