### ISSUE TITLE
Implement DAOProvider::findOnePickupPointById

### ISSUE THREAD

**Issue by igormukhingmailcom** [Setono/SyliusPickupPointPlugin#12]
As far as this not required right now, we leave this to future.
It will be implemented once I have some link to docs and credentials to test that.

**Comment by igormukhingmailcom** [comment]
Currently, to run DAO provider in dev environment, you should enable `cache` in plugin config.
You shouldn't use DAO at production until this issue fixed, as you will get exceptions once cached pickup points cleared.

**Comment by loevgaard** [comment]
Fixed in v1.0.0-beta.2
