### ISSUE TITLE
Making a new provider

### ISSUE THREAD

**Issue by ehibes** [Setono/SyliusPickupPointPlugin#36]
Hi, 

I'm trying to implement a new provider : TNT. I make a new Provider class that allows to display the points (for a given zipcode), that is ok.
However, on the admin part, to display PickupPoint info I need to implement  findPickupPoint function but TNT webservice doest not have any function to make that. I don't know how to make this, any ideas ?
Thanks

**Comment by igormukhingmailcom** [comment]
I'm out of context what TNT webservice have, but it maybe have some kind of arguments to limit pickup points list by pickup point identifier. Otherwise, as an (not too good) option, you can fetch all pickup points and then return only one of them based on identifier you're looking for at findPickupPoint

**Comment by ehibes** [comment]
Yes I tried this but fo fetch all pickup I need a zipcode at least. And the findPickupPoint argument is a PickPointCode without any zipcode. The bundle doesn't allow to overwrite PointPickup & PointPickupCode classes If I am not mistaken.

**Comment by loevgaard** [comment]
Hi @ehibes 

Can you share the API docs for TNT? A great help would also be to start creating a PR with your work.

**Comment by ehibes** [comment]
There is no doc for this 😬. 
It's a SOAP service => [http://www.tnt.fr/service/?wsdl](http://www.tnt.fr/service/?wsdl)
I use [winzou/tnt-express](https://github.com/winzou/tnt-express) lib.

**Comment by loevgaard** [comment]
If there is not way to get a single pickup point then maybe you should code your provider such that when you want to implement the [this method](https://github.com/Setono/SyliusPickupPointPlugin/blob/master/src/Provider/ProviderInterface.php#L32) then you should have a local database where you can fetch that pickup point.

Possibly you can use the already implemented local provider which populates a local database with all pickup points.

These are just thoughts. Let me hear what you think.

**Comment by ehibes** [comment]
To implement your method I need a PointPickupCode with a zipcode (to fetch all points on TNT), and because of different interfaces I can't overwrite PointPickupCode. 

To store points in local database, I need a function to fetch all points without parameter, but there is no function like that in TNT Api.

**Comment by loevgaard** [comment]
To fetch all pickup points I suppose you could have a static list of all postal codes and then loop through them and fetch all pickup points this way?

**Comment by ehibes** [comment]
Yes,  it can be a solution. However don't you think we can overwrite PointPickupCode to add zipcode into it? Just for my Provider of course.

**Comment by igormukhingmailcom** [comment]
I believe postcode is optional at original wsdl service. It required only at winzou's library.
See https://www.wsdl-analyzer.com/operation/operation/715499500?version=1&namespace=http%3A%2F%2Fcxf.ws.app.tnt.fr%2F&portTypeName=Services&operationName=dropOffPoints

**Comment by ehibes** [comment]
I tested with empty zipcode, soap returns me an error message : "The field 'zipCode' is mandatory. The field 'city' is mandatory"

**Comment by loevgaard** [comment]
Will close for now. Any new provider is obviously welcome in a PR :)
