### ISSUE TITLE
Allow extending plugin classes

### ISSUE THREAD

**Issue by rimas-kudelis** [Setono/SyliusPickupPointPlugin#47]
The `PickupPoint` entity class is currently marked as soft-final, and Doctrine mapping files are automatically applied. This makes the entity particularly difficult to extend. Please make it easier.
My use-case is we want to be able to enable/disable specific pickup points as we see fit.

Even more unexpectedly, the `PickupPointRepository` class is final, so in order to add new repository methods, I end up having to copy-paste the original ones, and that looks a bit suboptimal.

**Comment by loevgaard** [comment]
The repository was made non final in this commit: https://github.com/Setono/SyliusPickupPointPlugin/commit/67ea6918b31bf1f6fbf4130269fb08a9bde9cfa5
