### ISSUE TITLE
Store latitude and longitude as decimal numbers

### ISSUE THREAD

**Issue by rimas-kudelis** [Setono/SyliusPickupPointPlugin#48]
Hi! I'm wondering if there is any particular reason why latitude and longitude are stored as strings as opposed to fixed-precision decimal numbers. Was that a design decision or an oversight?

**Comment by loevgaard** [comment]
It was probably a quick thing where we just thought that those are float numbers and are easily represented by strings, but I guess we will make them floats/decimals :)

**Comment by loevgaard** [comment]
Would appreciate a review of this PR, @rimas-kudelis, if you have the time: https://github.com/Setono/SyliusPickupPointPlugin/pull/57 :)
